version: "3"
services:

  backend:
    container_name: backend
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on: 
      - db
    env_file:
      - backend/.env
    container_name: backend
    command: python main.py
    volumes:
      - ./backend:/home/src/
    ports:
      - "80:8000"

  db:
    container_name: mysql
    image: mysql:5.7
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=r00t
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456
    volumes: 
      - "sqldatavolume:/var/lib/mysql"
  
volumes:
  sqldatavolume:
